export const ROUTE_COPY_SLICE_RU = {
  'How swap works': 'Как работает swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Выберите активный signing wallet, укажите исходный актив, введите сумму и просмотрите доступные маршруты. Этот экран только строит котировки и варианты маршрутизации.\n\nSlippage защищает минимальную сумму, которую вы должны получить. Маршрут может быть видимым здесь, но оставаться непригодным к исполнению, пока не пройдут актуальная котировка и проверки самого маршрута.\n\nРеальная проверка ресурсов, защищенный минимум и финальная подпись происходят уже на шаге подтверждения, до отправки swap.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Выберите активный signing wallet, укажите актив, введите адрес получателя и сумму отправки. Адрес можно вставить, отсканировать по QR или взять из недавних получателей и сохраненных контактов.\n\nЭтот экран только подготавливает перевод. Проверка, сетевые условия и финальная подпись происходят на шаге подтверждения.\n\nMAX использует доступный к отправке баланс выбранного актива. Для защищенных активов может сохраняться обязательный dust-остаток вместо полного обнуления.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Используйте этот экран, чтобы подготовить прямую покупку 4TEEN через выбранный signing wallet. Введите сумму в TRX, и приложение покажет расчетное количество 4TEEN еще до подписи.\n\nDirect buy — это не swap. FourteenToken выпускает 4TEEN по правилам контракта, блокирует купленную партию на 14 дней и распределяет входящий TRX между ликвидностью, controller-side учетом и airdrop-направлением.\n\nContinue открывает шаг подтверждения. Именно там приложение собирает реальную транзакцию, проверяет ресурсы и только после этого просит passcode или биометрию.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Этот экран показывает статус social airdrop для выбранного кошелька. Это не общая история переводов. Сейчас живой claim flow работает через Telegram: приложение запускает wallet session, открывает бота и затем отслеживает, доступна ли награда, поставлена в очередь, заблокирована legacy-клеймом или уже получена.\n\nКарточка Telegram объединяет сразу три проверки: локальное состояние кошелька, текущее состояние bot session и on-chain состояние клейма. Поэтому ее метка может переключаться между available, verify now, session live, queued и received.\n\nОстальные social-карточки пока остаются rollout-заглушками. Они могут показывать уже полученные on-chain награды, но живой claim flow там еще не открыт.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Этот экран показывает signing key, локально сохраненный для этого кошелька. Во время экспорта ключ никогда не отправляется на серверы 4TEEN.\n\nПеред показом ключа приложение требует passcode или биометрию. Пока ключ виден, скриншоты блокируются, а сам ключ автоматически скрывается через одну минуту или при уходе приложения в фон.\n\nЛюбой, у кого есть этот private key, может подписывать транзакции от имени кошелька. Копируйте его только если храните офлайн и безопасно.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Этот экран показывает recovery phrase, локально сохраненную для этого кошелька. Во время экспорта фраза никогда не отправляется на серверы 4TEEN.\n\nПеред показом слов приложение требует passcode или биометрию. Пока фраза видна, скриншоты блокируются, а сама фраза автоматически скрывается через одну минуту или при уходе приложения в фон.\n\nЛюбой, у кого есть эти слова, может получить контроль над кошельком. Копируйте их только если храните фразу офлайн и безопасно.',
} as const;

export const ROUTE_COPY_SLICE_UZ = {
  'How swap works': 'Swap qanday ishlaydi',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Faol signing wallet’ni tanlang, kiruvchi aktivni belgilang, miqdorni kiriting va mavjud marshrutlarni ko‘rib chiqing. Bu ekran faqat quote va routing variantlarini tayyorlaydi.\n\nSlippage siz olishingiz kerak bo‘lgan minimal miqdorni himoya qiladi. Marshrut bu yerda ko‘rinishi mumkin, lekin hozirgi quote va route tekshiruvlari o‘tmaguncha hali bajarilmaydigan deb belgilanishi mumkin.\n\nHaqiqiy resource tekshiruvi, himoyalangan minimum va yakuniy imzo swap yuborilishidan oldingi tasdiqlash bosqichida bo‘ladi.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Faol signing wallet’ni tanlang, aktivni belgilang, qabul qiluvchi manzilini kiriting va yubormoqchi bo‘lgan miqdorni qo‘ying. Manzilni qo‘yish, QR skan qilish yoki yaqindagi qabul qiluvchilar va saqlangan kontaktlardan tanlash mumkin.\n\nBu ekran faqat transferni tayyorlaydi. Review, tarmoq tekshiruvlari va yakuniy imzo tasdiqlash bosqichida bo‘ladi.\n\nMAX tanlangan aktivning yuborish mumkin bo‘lgan balansidan foydalanadi. Himoyalangan aktivlar to‘liq nolga tushirish o‘rniga zarur dust zaxirasini qoldirishi mumkin.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Tanlangan signing wallet bilan to‘g‘ridan-to‘g‘ri 4TEEN xaridini tayyorlash uchun shu ekrandan foydalaning. TRX miqdorini kiriting va imzo qo‘yilishidan oldin ilova taxminiy olinadigan 4TEEN miqdorini ko‘rsatadi.\n\nDirect buy swap emas. FourteenToken kontrakt qoidalari bo‘yicha 4TEEN chiqaradi, sotib olingan partiyani 14 kunga lock qiladi va kiruvchi TRX’ni likvidlik, controller-side accounting va airdrop yo‘nalishiga taqsimlaydi.\n\nContinue tasdiqlash bosqichini ochadi. Aynan o‘sha yerda ilova haqiqiy tranzaksiyani tayyorlaydi, resource’larni tekshiradi va shundan keyingina passcode yoki biometrikani so‘raydi.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Bu ekran tanlangan hamyon uchun social airdrop holatini ko‘rsatadi. Bu oddiy transfer tarixi emas. Hozirgi live claim flow Telegram orqali ishlaydi: ilova wallet session’ni boshlaydi, botni ochadi va keyin mukofot mavjudmi, navbatdami, legacy claim bilan bloklanganmi yoki allaqachon olinganmi — shuni kuzatadi.\n\nTelegram kartasi bir vaqtning o‘zida uchta tekshiruvni birlashtiradi: lokal wallet holati, joriy bot session holati va on-chain claim holati. Shuning uchun uning belgisi available, verify now, session live, queued yoki received o‘rtasida o‘zgarishi mumkin.\n\nQolgan social kartalar hozircha rollout uchun placeholder bo‘lib turibdi. Ular allaqachon olingan on-chain mukofotlarni ko‘rsatishi mumkin, ammo live claim flow u yerda hali ochilmagan.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Bu ekran shu hamyon uchun lokal saqlangan signing key’ni ochadi. Eksport vaqtida kalit hech qachon 4TEEN serverlariga yuborilmaydi.\n\nKalit ko‘rsatilishidan oldin ilova passcode yoki biometrikani talab qiladi. Kalit ochiq turganda screenshot bloklanadi va u bir daqiqadan keyin yoki ilova fon holatiga o‘tganda avtomatik yashiriladi.\n\nBu private key’ga ega bo‘lgan har kim hamyon nomidan tranzaksiya imzolashi mumkin. Uni faqat oflayn va xavfsiz saqlayotgan bo‘lsangizgina nusxalang.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Bu ekran shu hamyon uchun lokal saqlangan recovery phrase’ni ochadi. Eksport vaqtida fraza hech qachon 4TEEN serverlariga yuborilmaydi.\n\nSo‘zlar ko‘rsatilishidan oldin ilova passcode yoki biometrikani talab qiladi. Fraza ko‘rinib turganda screenshot bloklanadi va u bir daqiqadan keyin yoki ilova fon holatiga o‘tganda avtomatik yashiriladi.\n\nBu so‘zlarga ega bo‘lgan har kim hamyonni boshqara oladi. Ularni faqat oflayn va xavfsiz saqlayotgan bo‘lsangizgina nusxalang.',
} as const;

export const ROUTE_COPY_SLICE_TR = {
  'How swap works': 'Swap nasıl çalışır',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Etkin signing wallet’i seçin, giriş varlığını belirleyin, miktarı girin ve mevcut rotaları inceleyin. Bu ekran yalnızca quote ve route seçeneklerini hazırlar.\n\nSlippage alacağınız minimum miktarı korur. Bir rota burada görünür olabilir ama mevcut quote ve route kontrolleri geçilene kadar yine de yürütülemez olarak işaretlenebilir.\n\nGerçek resource kontrolü, korunan minimum ve son imza, herhangi bir swap gönderilmeden önce onay adımında gerçekleşir.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Etkin signing wallet’i seçin, varlığı belirleyin, alıcı adresini girin ve göndermek istediğiniz miktarı ayarlayın. Adresi yapıştırabilir, QR kod tarayabilir veya son alıcılardan ve kayıtlı kişilerden seçebilirsiniz.\n\nBu ekran yalnızca transferi hazırlar. İnceleme, ağ kontrolleri ve son imza onay adımında gerçekleşir.\n\nMAX seçilen varlık için harcanabilir bakiyeyi kullanır. Korumalı varlıklar tam sıfırlamaya izin vermek yerine gerekli bir dust rezervi bırakabilir.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Seçilen signing wallet ile doğrudan 4TEEN satın alımını hazırlamak için bu ekranı kullanın. TRX miktarını girin; uygulama herhangi bir imza atmadan önce alacağınız tahmini 4TEEN miktarını gösterir.\n\nDirect buy bir swap değildir. FourteenToken, kontrat kurallarına göre 4TEEN üretir, satın alınan partiyi 14 gün kilitler ve gelen TRX’i likidite, controller-side accounting ve airdrop hattına yönlendirir.\n\nContinue onay adımını açar. Uygulama gerçek işlemi orada oluşturur, kaynakları kontrol eder ve ancak ondan sonra passcode veya biyometri ister.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Bu ekran seçili wallet için social airdrop durumunu gösterir. Genel bir transfer geçmişi değildir. Şu anda canlı claim akışı Telegram üzerindedir: uygulama bir wallet session başlatır, botu açar ve ödülün kullanılabilir, sırada, eski bir claim yüzünden engelli veya zaten alınmış olup olmadığını takip eder.\n\nTelegram kartı aynı anda üç kontrolü birleştirir: yerel wallet durumu, mevcut bot session durumu ve on-chain claim durumu. Bu yüzden etiketi available, verify now, session live, queued veya received arasında değişebilir.\n\nDiğer social kartlar şimdilik rollout placeholder’larıdır. Zaten alınmış on-chain ödülleri yine gösterebilirler, ancak canlı claim akışı henüz orada açık değildir.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Bu ekran, bu wallet için yerel olarak saklanan signing key’i gösterir. Export sırasında anahtar hiçbir zaman 4TEEN sunucularına gönderilmez.\n\nAnahtar gösterilmeden önce uygulama passcode veya biyometri ister. Görünür durumdayken ekran görüntüsü engellenir ve anahtar bir dakika sonra veya uygulama arka plana geçtiğinde otomatik olarak gizlenir.\n\nBu private key’e sahip olan herkes wallet adına işlem imzalayabilir. Onu yalnızca çevrimdışı ve güvenli şekilde saklıyorsanız kopyalayın.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Bu ekran, bu wallet için yerel olarak saklanan recovery phrase’i gösterir. Export sırasında ifade hiçbir zaman 4TEEN sunucularına gönderilmez.\n\nKelimeler gösterilmeden önce uygulama passcode veya biyometri ister. İfade görünür durumdayken ekran görüntüsü engellenir ve bir dakika sonra ya da uygulama arka plana geçtiğinde otomatik olarak gizlenir.\n\nBu kelimelere sahip olan herkes wallet’ı kontrol edebilir. Bunları yalnızca çevrimdışı ve güvenli şekilde saklıyorsanız kopyalayın.',
} as const;

export const ROUTE_COPY_SLICE_DE = {
  'How swap works': 'So funktioniert der Swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Wählen Sie die aktive Signing-Wallet, den Eingangs-Asset, geben Sie den Betrag ein und prüfen Sie die verfügbaren Routen. Dieser Bildschirm erstellt nur Quotes und Routing-Optionen.\n\nSlippage schützt den Mindestbetrag, den Sie erhalten. Eine Route kann hier sichtbar sein und trotzdem noch als nicht ausführbar markiert werden, bis die aktuelle Quote und die Routenprüfungen bestanden sind.\n\nDie echte Ressourcenprüfung, das geschützte Minimum und die endgültige Signatur erfolgen erst im Bestätigungsschritt, bevor ein Swap gesendet wird.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Wählen Sie die aktive Signing-Wallet, den Asset, geben Sie die Empfängeradresse ein und legen Sie den zu sendenden Betrag fest. Sie können eine Adresse einfügen, einen QR-Code scannen oder aus letzten Empfängern und gespeicherten Kontakten wählen.\n\nDieser Bildschirm bereitet nur die Überweisung vor. Prüfung, Netzwerk-Checks und die endgültige Signatur erfolgen im Bestätigungsschritt.\n\nMAX verwendet den verfügbaren Betrag des gewählten Assets. Geschützte Assets können einen erforderlichen Dust-Reservebetrag behalten, statt eine vollständige Nullstellung zu erlauben.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Nutzen Sie diesen Bildschirm, um mit der ausgewählten Signing-Wallet einen direkten 4TEEN-Kauf vorzubereiten. Geben Sie den TRX-Betrag ein, und die App zeigt die geschätzte Menge an 4TEEN an, die Sie erhalten, bevor etwas signiert wird.\n\nEin Direct Buy ist kein Swap. FourteenToken mintet 4TEEN nach Vertragsregeln, sperrt das gekaufte Paket für 14 Tage und verteilt eingehenden TRX auf Liquidität, controller-seitige Buchung und die Airdrop-Schiene.\n\nContinue öffnet den Bestätigungsschritt. Dort erstellt die App die echte Transaktion, prüft Ressourcen und fragt erst danach nach Passcode oder Biometrie.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Dieser Bildschirm zeigt den Social-Airdrop-Status der ausgewählten Wallet. Er ist keine allgemeine Transferhistorie. Der aktive Claim-Flow läuft derzeit über Telegram: Die App startet eine Wallet-Session, öffnet den Bot und verfolgt dann, ob die Belohnung verfügbar, in der Warteschlange, durch einen alten Claim blockiert oder bereits erhalten ist.\n\nDie Telegram-Karte kombiniert drei Prüfungen zugleich: den lokalen Wallet-Status, den aktuellen Bot-Session-Status und den On-Chain-Claim-Status. Deshalb kann ihr Label zwischen available, verify now, session live, queued oder received wechseln.\n\nDie anderen Social-Karten sind vorerst Rollout-Platzhalter. Sie können bereits beanspruchte On-Chain-Belohnungen anzeigen, aber der aktive Claim-Flow ist dort noch nicht geöffnet.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Dieser Bildschirm zeigt den lokal für diese Wallet gespeicherten Signierschlüssel. Der Schlüssel wird beim Export niemals an 4TEEN-Server gesendet.\n\nBevor der Schlüssel angezeigt wird, verlangt die App einen Passcode oder Biometrie. Solange er sichtbar ist, werden Screenshots blockiert und der Schlüssel wird nach einer Minute oder beim Wechsel der App in den Hintergrund automatisch verborgen.\n\nJeder mit diesem Private Key kann Transaktionen für die Wallet signieren. Kopieren Sie ihn nur, wenn Sie ihn offline und sicher aufbewahren.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Dieser Bildschirm zeigt die lokal für diese Wallet gespeicherte Recovery Phrase. Die Phrase wird beim Export niemals an 4TEEN-Server gesendet.\n\nBevor die Wörter angezeigt werden, verlangt die App einen Passcode oder Biometrie. Solange die Phrase sichtbar ist, werden Screenshots blockiert und sie wird nach einer Minute oder beim Wechsel der App in den Hintergrund automatisch verborgen.\n\nJeder mit diesen Wörtern kann die Wallet kontrollieren. Kopieren Sie sie nur, wenn Sie die Phrase offline und sicher aufbewahren.',
} as const;

export const ROUTE_COPY_SLICE_FR = {
  'How swap works': 'Comment fonctionne le swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Choisissez le wallet de signature actif, sélectionnez l’actif d’entrée, saisissez le montant et examinez les routes disponibles. Cet écran prépare uniquement les quotes et les options de routage.\n\nLe slippage protège le montant minimum que vous recevrez. Une route peut être visible ici tout en restant marquée comme non exécutable tant que la quote actuelle et les vérifications de route n’ont pas abouti.\n\nLe vrai contrôle des ressources, le minimum protégé et la signature finale interviennent lors de l’étape de confirmation, avant l’envoi du swap.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Choisissez le wallet de signature actif, sélectionnez l’actif, saisissez l’adresse du destinataire et le montant à envoyer. Vous pouvez coller une adresse, scanner un QR code ou choisir parmi les destinataires récents et les contacts enregistrés.\n\nCet écran prépare uniquement le transfert. La vérification, les contrôles réseau et la signature finale ont lieu à l’étape de confirmation.\n\nMAX utilise le solde réellement dépensable de l’actif sélectionné. Les actifs protégés peuvent conserver une réserve de dust requise au lieu d’autoriser une remise à zéro complète.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Utilisez cet écran pour préparer un achat direct de 4TEEN avec le wallet de signature sélectionné. Saisissez le montant en TRX et l’application affiche l’estimation de 4TEEN que vous recevrez avant toute signature.\n\nUn direct buy n’est pas un swap. FourteenToken mint 4TEEN selon les règles du contrat, verrouille le lot acheté pendant 14 jours et répartit le TRX entrant entre la liquidité, la comptabilité côté controller et le rail airdrop.\n\nContinue ouvre l’étape de confirmation. C’est là que l’application construit la vraie transaction, vérifie les ressources et ne demande le passcode ou la biométrie qu’ensuite.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Cet écran montre le statut social airdrop du wallet sélectionné. Ce n’est pas un historique de transfert générique. Pour l’instant, le flux de claim actif passe par Telegram : l’application démarre une session wallet, ouvre le bot, puis suit si la récompense est disponible, en file d’attente, bloquée par un ancien claim ou déjà reçue.\n\nLa carte Telegram combine trois contrôles en même temps : l’état local du wallet, l’état actuel de la session bot et l’état du claim on-chain. C’est pour cela que son libellé peut passer entre available, verify now, session live, queued ou received.\n\nLes autres cartes sociales sont encore des placeholders de rollout. Elles peuvent déjà afficher des récompenses on-chain déjà réclamées, mais le flux de claim actif n’y est pas encore ouvert.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Cet écran révèle la clé de signature stockée localement pour ce wallet. La clé n’est jamais envoyée aux serveurs 4TEEN pendant l’export.\n\nAvant son affichage, l’application exige le passcode ou la biométrie. Tant qu’elle reste visible, les captures d’écran sont bloquées et la clé se masque automatiquement après une minute ou lorsque l’application passe en arrière-plan.\n\nToute personne possédant cette private key peut signer des transactions depuis le wallet. Copiez-la uniquement si vous la conservez hors ligne et en sécurité.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Cet écran révèle la phrase de récupération stockée localement pour ce wallet. La phrase n’est jamais envoyée aux serveurs 4TEEN pendant l’export.\n\nAvant l’affichage des mots, l’application exige le passcode ou la biométrie. Tant que la phrase est visible, les captures d’écran sont bloquées et elle se masque automatiquement après une minute ou lorsque l’application passe en arrière-plan.\n\nToute personne possédant ces mots peut contrôler le wallet. Copiez-les uniquement si vous conservez la phrase hors ligne et en sécurité.',
} as const;

export const ROUTE_COPY_SLICE_ES = {
  'How swap works': 'Cómo funciona el swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Elige el signing wallet activo, selecciona el activo de entrada, introduce la cantidad y revisa las rutas disponibles. Esta pantalla solo construye cotizaciones y opciones de enrutamiento.\n\nEl slippage protege la cantidad mínima que recibirás. Una ruta puede verse aquí y aun así seguir marcada como no ejecutable hasta que pasen la cotización actual y las comprobaciones de la ruta.\n\nLa verificación real de recursos, el mínimo protegido y la firma final ocurren en el paso de confirmación, antes de enviar cualquier swap.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Elige el signing wallet activo, selecciona el activo, introduce la dirección del destinatario y define la cantidad que quieres enviar. Puedes pegar una dirección, escanear un código QR o elegir entre destinatarios recientes y contactos guardados.\n\nEsta pantalla solo prepara la transferencia. La revisión, las comprobaciones de red y la firma final ocurren en el paso de confirmación.\n\nMAX usa el saldo disponible para gastar del activo seleccionado. Los activos protegidos pueden mantener una reserva mínima de dust en lugar de permitir un vaciado total.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Usa esta pantalla para preparar una compra directa de 4TEEN con el signing wallet seleccionado. Introduce la cantidad de TRX y la app mostrará el 4TEEN estimado que recibirás antes de firmar nada.\n\nDirect buy no es un swap. FourteenToken acuña 4TEEN según las reglas del contrato, bloquea el lote comprado durante 14 días y distribuye el TRX entrante entre liquidez, contabilidad del controller y el canal de airdrop.\n\nContinue abre el paso de confirmación. Ahí es donde la app construye la transacción real, comprueba recursos y solo después pide passcode o biometría.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Esta pantalla muestra el estado del social airdrop para el wallet seleccionado. No es un historial genérico de transferencias. Ahora mismo el flujo de claim en vivo es Telegram: la app inicia una wallet session, abre el bot y luego sigue si la recompensa está disponible, en cola, bloqueada por un claim heredado o ya recibida.\n\nLa tarjeta de Telegram combina tres comprobaciones a la vez: el estado local del wallet, el estado actual de la bot session y el estado del claim on-chain. Por eso su etiqueta puede moverse entre available, verify now, session live, queued o received.\n\nLas otras tarjetas sociales son por ahora placeholders de rollout. Pueden seguir mostrando recompensas on-chain ya reclamadas, pero el flujo de claim en vivo todavía no está abierto allí.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Esta pantalla revela la clave de firma almacenada localmente para este wallet. La clave nunca se envía a los servidores de 4TEEN durante la exportación.\n\nAntes de mostrarla, la app exige passcode o biometría. Mientras la clave esté visible, las capturas de pantalla se bloquean y la clave se oculta automáticamente al cabo de un minuto o cuando la app pasa a segundo plano.\n\nCualquiera que tenga esta private key puede firmar transacciones desde el wallet. Cópiala solo si la vas a guardar offline y de forma segura.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Esta pantalla revela la recovery phrase almacenada localmente para este wallet. La frase nunca se envía a los servidores de 4TEEN durante la exportación.\n\nAntes de mostrar las palabras, la app exige passcode o biometría. Mientras la frase esté visible, las capturas de pantalla se bloquean y se oculta automáticamente al cabo de un minuto o cuando la app pasa a segundo plano.\n\nCualquiera que tenga estas palabras puede controlar el wallet. Cópialas solo si vas a guardar la frase offline y de forma segura.',
} as const;

export const ROUTE_COPY_SLICE_IT = {
  'How swap works': 'Come funziona lo swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Scegli il signing wallet attivo, seleziona l’asset in ingresso, inserisci l’importo e rivedi i percorsi disponibili. Questa schermata costruisce solo quote e opzioni di routing.\n\nLo slippage protegge l’importo minimo che riceverai. Un percorso può essere visibile qui e risultare comunque non eseguibile finché la quote attuale e i controlli sul percorso non vengono superati.\n\nIl vero controllo delle risorse, il minimo protetto e la firma finale avvengono nel passaggio di conferma, prima che venga inviato qualsiasi swap.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Scegli il signing wallet attivo, seleziona l’asset, inserisci l’indirizzo del destinatario e imposta l’importo da inviare. Puoi incollare un indirizzo, scansionare un QR code oppure scegliere tra i destinatari recenti e i contatti salvati.\n\nQuesta schermata prepara soltanto il trasferimento. Revisione, controlli di rete e firma finale avvengono nel passaggio di conferma.\n\nMAX usa il saldo effettivamente spendibile dell’asset selezionato. Gli asset protetti possono mantenere una riserva dust richiesta invece di consentire un azzeramento completo.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Usa questa schermata per preparare un acquisto diretto di 4TEEN con il signing wallet selezionato. Inserisci l’importo in TRX e l’app mostrerà la quantità stimata di 4TEEN che riceverai prima che venga firmato qualcosa.\n\nUn direct buy non è uno swap. FourteenToken emette 4TEEN secondo le regole del contratto, blocca il lotto acquistato per 14 giorni e instrada il TRX in ingresso tra liquidità, contabilità lato controller e canale airdrop.\n\nContinue apre il passaggio di conferma. È lì che l’app costruisce la transazione reale, controlla le risorse e solo dopo chiede passcode o biometria.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Questa schermata mostra lo stato del social airdrop per il wallet selezionato. Non è una cronologia generica dei trasferimenti. In questo momento il live claim flow passa da Telegram: l’app avvia una wallet session, apre il bot e poi verifica se la ricompensa è disponibile, in coda, bloccata da un legacy claim oppure già ricevuta.\n\nLa card Telegram combina tre controlli contemporaneamente: stato locale del wallet, stato attuale della bot session e stato del claim on-chain. Per questo la sua etichetta può passare tra available, verify now, session live, queued o received.\n\nLe altre card social per ora sono placeholder di rollout. Possono comunque mostrare ricompense on-chain già riscosse, ma il live claim flow lì non è ancora aperto.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Questa schermata mostra la chiave di firma memorizzata localmente per questo wallet. Durante l’esportazione la chiave non viene mai inviata ai server 4TEEN.\n\nPrima che venga mostrata, l’app richiede passcode o biometria. Finché è visibile, gli screenshot sono bloccati e la chiave viene nascosta automaticamente dopo un minuto o quando l’app passa in background.\n\nChiunque possieda questa private key può firmare transazioni dal wallet. Copiala solo se la conserverai offline e in modo sicuro.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Questa schermata mostra la recovery phrase memorizzata localmente per questo wallet. Durante l’esportazione la frase non viene mai inviata ai server 4TEEN.\n\nPrima che le parole vengano mostrate, l’app richiede passcode o biometria. Finché la frase è visibile, gli screenshot sono bloccati e si nasconde automaticamente dopo un minuto o quando l’app passa in background.\n\nChiunque possieda queste parole può controllare il wallet. Copiale solo se conserverai la frase offline e in modo sicuro.',
} as const;

export const ROUTE_COPY_SLICE_PT = {
  'How swap works': 'Como o swap funciona',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Escolha a signing wallet ativa, selecione o ativo de entrada, informe o valor e reveja as rotas disponíveis. Este ecrã apenas monta quotes e opções de routing.\n\nO slippage protege o valor mínimo que irá receber. Uma rota pode aparecer aqui e ainda assim continuar marcada como não executável até que a quote atual e as verificações da rota passem.\n\nA verificação real de recursos, o mínimo protegido e a assinatura final acontecem no passo de confirmação, antes de qualquer swap ser enviado.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Escolha a signing wallet ativa, selecione o ativo, introduza o endereço do destinatário e defina o valor a enviar. Pode colar um endereço, ler um QR code ou escolher entre destinatários recentes e contactos guardados.\n\nEste ecrã apenas prepara a transferência. A revisão, as verificações de rede e a assinatura final acontecem no passo de confirmação.\n\nMAX usa o saldo realmente utilizável do ativo selecionado. Ativos protegidos podem manter uma reserva dust necessária em vez de permitir esgotar tudo até zero.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Use este ecrã para preparar uma compra direta de 4TEEN com a signing wallet selecionada. Introduza o valor em TRX e a app mostra a quantidade estimada de 4TEEN que irá receber antes de qualquer assinatura.\n\nDirect buy não é um swap. FourteenToken faz mint de 4TEEN pelas regras do contrato, bloqueia o lote comprado durante 14 dias e encaminha o TRX recebido por liquidez, contabilidade do controller e trilho de airdrop.\n\nContinue abre o passo de confirmação. É aí que a app monta a transação real, verifica recursos e só depois pede passcode ou biometria.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Este ecrã mostra o estado do social airdrop para a wallet selecionada. Não é um histórico genérico de transferências. Neste momento o live claim flow funciona via Telegram: a app inicia uma wallet session, abre o bot e depois acompanha se a recompensa está disponível, em fila, bloqueada por um legacy claim ou já recebida.\n\nO cartão do Telegram combina três verificações ao mesmo tempo: estado local da wallet, estado atual da bot session e estado do claim on-chain. Por isso o rótulo pode mudar entre available, verify now, session live, queued ou received.\n\nOs outros cartões sociais são placeholders de rollout por agora. Ainda podem mostrar recompensas on-chain já reclamadas, mas o live claim flow ainda não está aberto nesses canais.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Este ecrã revela a signing key guardada localmente para esta wallet. A chave nunca é enviada para os servidores da 4TEEN durante a exportação.\n\nAntes de a chave ser mostrada, a app exige passcode ou biometria. Enquanto estiver visível, as capturas de ecrã são bloqueadas e a chave esconde-se automaticamente ao fim de um minuto ou quando a app passa para segundo plano.\n\nQualquer pessoa com esta private key pode assinar transações a partir da wallet. Copie-a apenas se a estiver a guardar offline e em segurança.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Este ecrã revela a recovery phrase guardada localmente para esta wallet. A frase nunca é enviada para os servidores da 4TEEN durante a exportação.\n\nAntes de as palavras serem mostradas, a app exige passcode ou biometria. Enquanto a frase estiver visível, as capturas de ecrã são bloqueadas e ela esconde-se automaticamente ao fim de um minuto ou quando a app passa para segundo plano.\n\nQualquer pessoa com estas palavras pode controlar a wallet. Copie-as apenas se guardar a frase offline e em segurança.',
} as const;

export const ROUTE_COPY_SLICE_NL = {
  'How swap works': 'Hoe swap werkt',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Kies de actieve signing wallet, selecteer het invoer-asset, vul het bedrag in en bekijk de beschikbare routes. Dit scherm bouwt alleen quotes en routingopties op.\n\nSlippage beschermt het minimale bedrag dat je ontvangt. Een route kan hier zichtbaar zijn en toch nog als niet uitvoerbaar zijn gemarkeerd totdat de huidige quote en routechecks slagen.\n\nDe echte resource-check, het beschermde minimum en de uiteindelijke handtekening gebeuren in de bevestigingsstap, voordat een swap wordt verzonden.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Kies de actieve signing wallet, selecteer het asset, vul het ontvangstadres in en stel het bedrag in dat je wilt verzenden. Je kunt een adres plakken, een QR-code scannen of kiezen uit recente ontvangers en opgeslagen contacten.\n\nDit scherm bereidt alleen de overdracht voor. Controle, netwerkchecks en de uiteindelijke handtekening gebeuren in de bevestigingsstap.\n\nMAX gebruikt het besteedbare saldo van het geselecteerde asset. Beschermde assets kunnen een vereiste dust-reserve behouden in plaats van volledige nulstelling toe te laten.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Gebruik dit scherm om een directe aankoop van 4TEEN voor te bereiden met de geselecteerde signing wallet. Voer het TRX-bedrag in en de app toont de geschatte hoeveelheid 4TEEN die je ontvangt voordat er iets wordt ondertekend.\n\nEen direct buy is geen swap. FourteenToken mint 4TEEN volgens de contractregels, vergrendelt de gekochte batch 14 dagen en verdeelt de binnenkomende TRX over liquiditeit, controller-side accounting en het airdrop-spoor.\n\nContinue opent de bevestigingsstap. Daar bouwt de app de echte transactie op, controleert resources en vraagt pas daarna om passcode of biometrie.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Dit scherm toont de social-airdropstatus voor de geselecteerde wallet. Het is geen algemene transfergeschiedenis. Op dit moment loopt de live claim-flow via Telegram: de app start een wallet session, opent de bot en volgt daarna of de beloning beschikbaar is, in de wachtrij staat, door een legacy claim is geblokkeerd of al is ontvangen.\n\nDe Telegram-kaart combineert tegelijk drie controles: lokale walletstatus, huidige bot-sessionstatus en on-chain claimstatus. Daarom kan het label wisselen tussen available, verify now, session live, queued of received.\n\nDe andere social-kaarten zijn voorlopig rollout-placeholders. Ze kunnen al geclaimde on-chain beloningen tonen, maar de live claim-flow is daar nog niet geopend.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Dit scherm onthult de signing key die lokaal voor deze wallet is opgeslagen. Tijdens het exporteren wordt de sleutel nooit naar 4TEEN-servers gestuurd.\n\nVoordat de sleutel wordt getoond, vereist de app een passcode of biometrie. Terwijl hij zichtbaar is, worden screenshots geblokkeerd en wordt de sleutel na één minuut of zodra de app naar de achtergrond gaat automatisch verborgen.\n\nIedereen met deze private key kan transacties vanuit de wallet ondertekenen. Kopieer hem alleen als je hem offline en veilig bewaart.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Dit scherm onthult de recovery phrase die lokaal voor deze wallet is opgeslagen. Tijdens het exporteren wordt de phrase nooit naar 4TEEN-servers gestuurd.\n\nVoordat de woorden worden getoond, vereist de app een passcode of biometrie. Terwijl de phrase zichtbaar is, worden screenshots geblokkeerd en wordt zij na één minuut of zodra de app naar de achtergrond gaat automatisch verborgen.\n\nIedereen met deze woorden kan de wallet beheren. Kopieer ze alleen als je de phrase offline en veilig bewaart.',
} as const;

export const ROUTE_COPY_SLICE_PL = {
  'How swap works': 'Jak działa swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'Wybierz aktywny signing wallet, wskaż aktywo wejściowe, wpisz kwotę i przejrzyj dostępne ścieżki. Ten ekran buduje jedynie quote’y i opcje routingu.\n\nSlippage chroni minimalną kwotę, którą otrzymasz. Trasa może być tutaj widoczna, a mimo to nadal oznaczona jako niewykonalna, dopóki bieżący quote i kontrole trasy nie przejdą pomyślnie.\n\nRzeczywiste sprawdzenie zasobów, chronione minimum i końcowy podpis odbywają się dopiero na etapie potwierdzenia, zanim jakikolwiek swap zostanie wysłany.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'Wybierz aktywny signing wallet, wskaż aktywo, wpisz adres odbiorcy i ustaw kwotę, którą chcesz wysłać. Możesz wkleić adres, zeskanować kod QR albo wybrać odbiorcę z ostatnich adresów i zapisanych kontaktów.\n\nTen ekran jedynie przygotowuje transfer. Weryfikacja, kontrole sieciowe i końcowy podpis odbywają się na etapie potwierdzenia.\n\nMAX używa salda dostępnego do wydania dla wybranego aktywa. Chronione aktywa mogą pozostawiać wymaganą rezerwę dust zamiast pozwalać na pełne wyzerowanie.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'Użyj tego ekranu, aby przygotować bezpośredni zakup 4TEEN za pomocą wybranego signing walleta. Wpisz kwotę TRX, a aplikacja pokaże szacowaną ilość 4TEEN, którą otrzymasz, zanim cokolwiek podpiszesz.\n\nDirect buy nie jest swapem. FourteenToken mintuje 4TEEN zgodnie z zasadami kontraktu, blokuje zakupioną partię na 14 dni i kieruje przychodzący TRX do płynności, księgowości po stronie controllera oraz szyny airdropowej.\n\nContinue otwiera etap potwierdzenia. To tam aplikacja buduje prawdziwą transakcję, sprawdza zasoby i dopiero wtedy prosi o passcode albo biometrię.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'Ten ekran pokazuje status social airdrop dla wybranego walleta. To nie jest ogólna historia transferów. Obecnie aktywny claim flow działa przez Telegram: aplikacja uruchamia wallet session, otwiera bota, a potem śledzi, czy nagroda jest dostępna, znajduje się w kolejce, jest zablokowana przez stary claim lub została już odebrana.\n\nKarta Telegram łączy jednocześnie trzy kontrole: lokalny stan walleta, bieżący stan bot session oraz stan claimu on-chain. Dlatego jej etykieta może zmieniać się między available, verify now, session live, queued i received.\n\nPozostałe karty social są na razie placeholderami rolloutowymi. Mogą nadal pokazywać już odebrane nagrody on-chain, ale aktywny claim flow nie jest tam jeszcze otwarty.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'Ten ekran ujawnia klucz podpisujący przechowywany lokalnie dla tego walleta. Klucz nigdy nie jest wysyłany na serwery 4TEEN podczas eksportu.\n\nZanim klucz zostanie pokazany, aplikacja wymaga passcode’u lub biometrii. Gdy jest widoczny, zrzuty ekranu są blokowane, a sam klucz chowa się automatycznie po minucie lub gdy aplikacja schodzi do tła.\n\nKażdy, kto posiada ten private key, może podpisywać transakcje z walleta. Kopiuj go tylko wtedy, gdy przechowujesz go offline i bezpiecznie.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'Ten ekran ujawnia recovery phrase przechowywaną lokalnie dla tego walleta. Fraza nigdy nie jest wysyłana na serwery 4TEEN podczas eksportu.\n\nZanim słowa zostaną pokazane, aplikacja wymaga passcode’u lub biometrii. Gdy fraza jest widoczna, zrzuty ekranu są blokowane, a sama fraza chowa się automatycznie po minucie lub gdy aplikacja schodzi do tła.\n\nKażdy, kto zna te słowa, może przejąć kontrolę nad walletem. Kopiuj je tylko wtedy, gdy przechowujesz frazę offline i bezpiecznie.',
} as const;

export const ROUTE_COPY_SLICE_AR = {
  'How swap works': 'كيف يعمل الـ swap',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'اختر signing wallet النشط، وحدد الأصل الداخل، وأدخل المبلغ، ثم راجع المسارات المتاحة. هذا الشاشة تبني فقط الـ quotes وخيارات التوجيه.\n\nيحمي slippage الحد الأدنى الذي ستتلقاه. قد يكون المسار ظاهرًا هنا ومع ذلك يبقى معلّمًا على أنه غير قابل للتنفيذ حتى تمرّ الـ quote الحالية وفحوصات المسار.\n\nالفحص الحقيقي للموارد، والحد الأدنى المحمي، والتوقيع النهائي يحدثون في خطوة التأكيد قبل إرسال أي swap.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'اختر signing wallet النشط، وحدد الأصل، وأدخل عنوان المستلم، ثم عيّن المبلغ الذي تريد إرساله. يمكنك لصق عنوان، أو مسح QR، أو الاختيار من المستلمين الأخيرين وجهات الاتصال المحفوظة.\n\nهذه الشاشة تجهّز التحويل فقط. المراجعة، وفحوصات الشبكة، والتوقيع النهائي تحدث في خطوة التأكيد.\n\nيستخدم MAX الرصيد القابل للإنفاق للأصل المحدد. وقد تحتفظ الأصول المحمية باحتياطي dust مطلوب بدل السماح بتصفير الرصيد بالكامل.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'استخدم هذه الشاشة لتحضير شراء مباشر لـ 4TEEN باستخدام signing wallet المحدد. أدخل مبلغ TRX وسيعرض التطبيق كمية 4TEEN التقديرية التي ستستلمها قبل توقيع أي شيء.\n\nDirect buy ليس swap. يقوم FourteenToken بعمل mint لـ 4TEEN وفق قواعد العقد، ويقفل الدفعة المشتراة لمدة 14 يومًا، ويوزع TRX الداخل بين السيولة والمحاسبة من جهة controller ومسار airdrop.\n\nيفتح Continue خطوة التأكيد. هناك يبني التطبيق المعاملة الحقيقية، ويفحص الموارد، وبعد ذلك فقط يطلب passcode أو البيومتريا.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'تعرض هذه الشاشة حالة social airdrop للمحفظة المحددة. وهي ليست سجل تحويلات عام. حاليًا يعمل live claim flow عبر Telegram: يبدأ التطبيق wallet session، ويفتح البوت، ثم يتتبع ما إذا كانت المكافأة متاحة أو في قائمة الانتظار أو محجوبة بسبب legacy claim أو تم استلامها بالفعل.\n\nتجمع بطاقة Telegram ثلاث عمليات تحقق في وقت واحد: حالة wallet المحلية، وحالة bot session الحالية، وحالة claim على السلسلة. لذلك يمكن أن ينتقل وسمها بين available و verify now و session live و queued و received.\n\nأما البطاقات الاجتماعية الأخرى فهي placeholders لمرحلة rollout في الوقت الحالي. وقد تظل تعرض مكافآت on-chain تم استلامها بالفعل، لكن live claim flow لم يُفتح هناك بعد.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'تعرض هذه الشاشة مفتاح التوقيع المخزن محليًا لهذه المحفظة. ولا يتم إرسال المفتاح أبدًا إلى خوادم 4TEEN أثناء التصدير.\n\nقبل عرض المفتاح، يطلب التطبيق passcode أو البيومتريا. وأثناء ظهوره، يتم حظر لقطات الشاشة، ويختفي المفتاح تلقائيًا بعد دقيقة واحدة أو عندما ينتقل التطبيق إلى الخلفية.\n\nيمكن لأي شخص يملك هذا الـ private key أن يوقّع معاملات من المحفظة. انسخه فقط إذا كنت ستخزنه خارج الإنترنت وبشكل آمن.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'تعرض هذه الشاشة recovery phrase المخزنة محليًا لهذه المحفظة. ولا يتم إرسال العبارة أبدًا إلى خوادم 4TEEN أثناء التصدير.\n\nقبل عرض الكلمات، يطلب التطبيق passcode أو البيومتريا. وأثناء ظهور العبارة، يتم حظر لقطات الشاشة، وتختفي تلقائيًا بعد دقيقة واحدة أو عندما ينتقل التطبيق إلى الخلفية.\n\nيمكن لأي شخص يملك هذه الكلمات أن يتحكم بالمحفظة. انسخها فقط إذا كنت ستخزن العبارة خارج الإنترنت وبشكل آمن.',
} as const;

export const ROUTE_COPY_SLICE_HI = {
  'How swap works': 'स्वैप कैसे काम करता है',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    'सक्रिय signing wallet चुनें, input asset चुनें, राशि दर्ज करें और उपलब्ध routes की समीक्षा करें. यह स्क्रीन केवल quotes और routing options बनाती है.\n\nSlippage उस न्यूनतम राशि की रक्षा करता है जो आपको मिलेगी. कोई route यहां दिखाई दे सकता है और फिर भी current quote और route checks पास होने तक non-executable चिह्नित रह सकता है.\n\nवास्तविक resource check, protected minimum और final signature confirmation step पर होते हैं, किसी भी swap के भेजे जाने से पहले.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    'सक्रिय signing wallet चुनें, asset चुनें, recipient address दर्ज करें और वह राशि सेट करें जिसे आप भेजना चाहते हैं. आप address paste कर सकते हैं, QR code scan कर सकते हैं, या recent recipients और saved contacts में से चुन सकते हैं.\n\nयह स्क्रीन केवल transfer तैयार करती है. Review, network checks और final signature confirmation step पर होते हैं.\n\nMAX चुने गए asset के spendable balance का उपयोग करता है. Protected assets पूरा zero-out करने के बजाय आवश्यक dust reserve बनाए रख सकते हैं.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    'चुने गए signing wallet के साथ direct 4TEEN purchase तैयार करने के लिए इस स्क्रीन का उपयोग करें. TRX राशि दर्ज करें और ऐप किसी भी signature से पहले अनुमानित 4TEEN दिखाएगा जो आपको मिलेगा.\n\nDirect buy कोई swap नहीं है. FourteenToken contract rules के अनुसार 4TEEN mint करता है, खरीदे गए batch को 14 दिनों के लिए lock करता है, और आने वाले TRX को liquidity, controller-side accounting और airdrop rail में route करता है.\n\nContinue confirmation step खोलता है. वहीं ऐप वास्तविक transaction बनाता है, resources जांचता है, और उसके बाद ही passcode या biometrics मांगता है.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'यह स्क्रीन चुने गए wallet के लिए social airdrop status दिखाती है. यह कोई generic transfer history नहीं है. अभी live claim flow Telegram के जरिए चलता है: ऐप एक wallet session शुरू करता है, bot खोलता है, और फिर यह ट्रैक करता है कि reward उपलब्ध है, queue में है, किसी legacy claim से blocked है, या पहले ही मिल चुकी है.\n\nTelegram card एक साथ तीन checks जोड़ती है: local wallet state, current bot session state, और on-chain claim state. इसी वजह से इसका label available, verify now, session live, queued या received के बीच बदल सकता है.\n\nबाकी social cards फिलहाल rollout placeholders हैं. वे पहले से claimed on-chain rewards दिखा सकती हैं, लेकिन live claim flow वहां अभी खुला नहीं है.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'यह स्क्रीन इस wallet के लिए locally stored signing key दिखाती है. Export के दौरान key कभी भी 4TEEN servers को नहीं भेजी जाती.\n\nKey दिखाने से पहले ऐप passcode या biometrics मांगता है. जब तक यह visible रहती है, screenshots block रहते हैं और key एक मिनट बाद या ऐप background में जाते ही अपने आप छिप जाती है.\n\nजिसके पास यह private key है, वह wallet से transactions sign कर सकता है. इसे तभी copy करें जब आप इसे offline और securely store कर रहे हों.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'यह स्क्रीन इस wallet के लिए locally stored recovery phrase दिखाती है. Export के दौरान phrase कभी भी 4TEEN servers को नहीं भेजी जाती.\n\nWords दिखाने से पहले ऐप passcode या biometrics मांगता है. जब तक phrase visible रहती है, screenshots block रहते हैं और phrase एक मिनट बाद या ऐप background में जाते ही अपने आप छिप जाती है.\n\nजिसके पास ये शब्द हैं, वह wallet को नियंत्रित कर सकता है. इन्हें तभी copy करें जब आप phrase को offline और securely store कर रहे हों.',
} as const;

export const ROUTE_COPY_SLICE_JA = {
  'How swap works': 'Swapの仕組み',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    '有効なsigning walletを選び、入力資産を指定し、数量を入力して、利用可能なルートを確認します。この画面は価格見積もりとルーティング候補を作成するためのものです。\n\nSlippageは、受け取る最低数量を保護します。ここでルートが見えていても、現在の見積もりとルートチェックを通過するまでは実行不可として扱われることがあります。\n\n実際のリソース確認、保護された最小受取量、最終署名は、swapを送信する前の確認ステップで行われます。',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    '有効なsigning walletを選び、資産を指定し、受取先アドレスと送金額を入力します。アドレスは貼り付け、QRスキャン、最近の宛先や保存済み連絡先からの選択ができます。\n\nこの画面は送金の準備だけを行います。確認、ネットワークチェック、最終署名は確認ステップで行われます。\n\nMAXは選択した資産の送金可能残高を使用します。保護対象の資産では、完全にゼロにせず必要なdust予約を残すことがあります。',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    '選択したsigning walletで4TEENを直接購入する準備をするための画面です。TRX額を入力すると、何も署名する前に受け取る見込みの4TEEN数量が表示されます。\n\nDirect buyはswapではありません。FourteenTokenは契約ルールに従って4TEENをmintし、購入分を14日間ロックし、入ってきたTRXを流動性、controller-side accounting、airdropレールへ振り分けます。\n\nContinueで確認ステップが開きます。そこではじめてアプリが実際のトランザクションを組み立て、リソースを確認し、その後でpasscodeや生体認証を求めます。',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    'この画面は、選択したwalletのsocial airdrop状況を表示します。一般的な送金履歴ではありません。現在、実際に使えるclaimフローはTelegramです。アプリがwallet sessionを開始し、botを開き、その後で報酬が利用可能か、キュー待ちか、旧claimでブロックされているか、すでに受け取られているかを追跡します。\n\nTelegramカードは、ローカルwallet状態、現在のbot session状態、on-chainのclaim状態という3つの確認を同時にまとめています。そのためラベルはavailable、verify now、session live、queued、receivedの間で変化します。\n\n他のsocialカードは今のところrollout用のプレースホルダーです。すでに受け取られたon-chain報酬を表示することはありますが、実際のclaimフローはまだ開いていません。',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    'この画面は、このwalletのためにローカル保存されている署名鍵を表示します。エクスポート中に鍵が4TEENのサーバーへ送られることはありません。\n\n鍵を表示する前に、アプリはpasscodeまたは生体認証を要求します。表示中はスクリーンショットがブロックされ、1分後またはアプリがバックグラウンドに移ると自動的に鍵が隠れます。\n\nこのprivate keyを持つ人は誰でもwalletからトランザクションに署名できます。オフラインで安全に保管する場合にのみコピーしてください。',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    'この画面は、このwalletのためにローカル保存されているrecovery phraseを表示します。エクスポート中にphraseが4TEENのサーバーへ送られることはありません。\n\n単語を表示する前に、アプリはpasscodeまたは生体認証を要求します。phraseが表示中はスクリーンショットがブロックされ、1分後またはアプリがバックグラウンドに移ると自動的に隠れます。\n\nこれらの単語を持つ人はwalletを制御できます。オフラインで安全に保管する場合にのみコピーしてください。',
} as const;

export const ROUTE_COPY_SLICE_ZH_CN = {
  'How swap works': 'Swap 如何运作',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    '选择当前激活的 signing wallet、输入资产、数量，并查看可用路由。这个页面只负责构建报价和路由选项。\n\nSlippage 用来保护你能收到的最小数量。某条路由即使在这里可见，也可能在当前报价和路由检查通过之前仍被标记为不可执行。\n\n真正的资源检查、受保护的最低到手量以及最终签名，都发生在发送 swap 之前的确认步骤里。',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    '选择当前激活的 signing wallet、资产、收款地址以及要发送的数量。你可以粘贴地址、扫描二维码，或者从最近收款人和已保存联系人中选择。\n\n这个页面只负责准备转账。复核、网络检查和最终签名都发生在确认步骤里。\n\nMAX 会使用所选资产可支配的余额。对于受保护资产，系统可能会保留必要的 dust 余额，而不是允许完全归零。',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    '使用这个页面为所选 signing wallet 准备一次直接购买 4TEEN。输入 TRX 数量后，在任何签名发生之前，应用会先显示你预计收到的 4TEEN 数量。\n\nDirect buy 不是 swap。FourteenToken 会按照合约规则铸造 4TEEN，将购买批次锁定 14 天，并把进入的 TRX 分配到流动性、controller-side accounting 和 airdrop 轨道。\n\nContinue 会打开确认步骤。应用会在那里构建真实交易、检查资源，然后才要求输入 passcode 或生物识别。',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    '这个页面显示所选钱包的 social airdrop 状态。它不是一个通用转账历史。当前真正可用的 claim 流程只在 Telegram：应用会启动 wallet session、打开 bot，然后跟踪奖励是可领取、排队中、被旧 claim 阻塞，还是已经到账。\n\nTelegram 卡片同时结合了三项检查：本地钱包状态、当前 bot session 状态，以及链上的 claim 状态。这也是为什么它的标签会在 available、verify now、session live、queued 和 received 之间切换。\n\n其他社交卡片目前仍然只是 rollout 占位项。它们可能会显示已经领取过的链上奖励，但 live claim flow 还没有在那些渠道开放。',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    '这个页面会显示为该钱包保存在本地的签名密钥。导出过程中，这个密钥绝不会发送到 4TEEN 服务器。\n\n在密钥显示之前，应用会要求 passcode 或生物识别。密钥可见期间，截图会被阻止；一分钟后或应用退到后台时，密钥会自动隐藏。\n\n任何拿到这个 private key 的人都能代表该钱包签名交易。只有在你会离线且安全保存它的情况下，才应该复制它。',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    '这个页面会显示为该钱包保存在本地的 recovery phrase。导出过程中，这段短语绝不会发送到 4TEEN 服务器。\n\n在单词显示之前，应用会要求 passcode 或生物识别。短语可见期间，截图会被阻止；一分钟后或应用退到后台时，短语会自动隐藏。\n\n任何拿到这些单词的人都能控制钱包。只有在你会离线且安全保存这段短语的情况下，才应该复制它。',
} as const;

export const ROUTE_COPY_SLICE_KO = {
  'How swap works': 'Swap이 작동하는 방식',
  'Choose the active signing wallet, select the input asset, enter the amount, and review the available routes. This screen builds quotes and routing options only.\n\nSlippage protects the minimum amount you receive. A route can be visible here and still be marked as not executable until the current quote and route checks pass.\n\nThe real resource check, protected minimum, and final signature happen on the confirmation step before any swap is sent.':
    '활성 signing wallet을 선택하고, 입력 자산과 수량을 정한 뒤, 사용 가능한 경로를 검토하세요. 이 화면은 quote와 routing 옵션만 구성합니다.\n\nSlippage는 여러분이 받게 될 최소 수량을 보호합니다. 어떤 route는 여기서 보이더라도 현재 quote와 route 검사를 통과하기 전까지는 실행 불가로 표시될 수 있습니다.\n\n실제 resource 확인, 보호된 최소 수령량, 최종 서명은 swap을 보내기 전의 confirmation 단계에서 이뤄집니다.',
  'Choose the active signing wallet, select the asset, enter the recipient address, and set the amount you want to send. You can paste an address, scan a QR code, or pick from recent recipients and saved contacts.\n\nThis screen prepares the transfer only. Review, network checks, and the final signature happen on the confirmation step.\n\nMAX uses the spendable balance for the selected asset. Protected assets may keep a required dust reserve instead of allowing a full zero-out.':
    '활성 signing wallet을 선택하고, 자산을 고른 뒤, 수신자 주소와 보낼 금액을 입력하세요. 주소를 붙여 넣거나 QR 코드를 스캔할 수도 있고, 최근 수신자나 저장된 연락처에서 고를 수도 있습니다.\n\n이 화면은 전송 준비만 담당합니다. 검토, 네트워크 확인, 최종 서명은 confirmation 단계에서 이뤄집니다.\n\nMAX는 선택한 자산의 실제 사용 가능한 잔액을 사용합니다. 보호된 자산은 완전한 zero-out 대신 필요한 dust reserve를 남길 수 있습니다.',
  'Use this screen to prepare a direct 4TEEN purchase with the selected signing wallet. Enter the TRX amount and the app shows the estimated 4TEEN you will receive before anything is signed.\n\nDirect buy is not a swap. FourteenToken mints 4TEEN by contract rules, locks the purchased batch for 14 days, and routes the incoming TRX across liquidity, controller-side accounting, and the airdrop rail.\n\nContinue opens the confirmation step. That is where the app builds the real transaction, checks resources, and only then asks for passcode or biometrics.':
    '선택한 signing wallet으로 직접 4TEEN 구매를 준비하려면 이 화면을 사용하세요. TRX 금액을 입력하면, 어떤 서명도 하기 전에 받을 것으로 예상되는 4TEEN 수량이 먼저 표시됩니다.\n\nDirect buy는 swap이 아닙니다. FourteenToken은 계약 규칙에 따라 4TEEN을 mint하고, 구매한 배치를 14일 동안 잠그며, 들어오는 TRX를 liquidity, controller-side accounting, airdrop rail로 분배합니다.\n\nContinue를 누르면 confirmation 단계가 열립니다. 그곳에서 앱이 실제 거래를 구성하고 resources를 확인한 뒤, 그 다음에야 passcode나 생체인증을 요청합니다.',
  'This screen shows social airdrop status for the selected wallet. It is not a generic transfer history. Right now the live claim flow is Telegram: the app starts a wallet session, opens the bot, and then tracks whether the reward is available, queued, blocked by a legacy claim, or already received.\n\nThe Telegram card combines three checks at once: local wallet state, current bot session state, and on-chain claim state. That is why its label can move between available, verify now, session live, queued, or received.\n\nThe other social cards are rollout placeholders for now. They may still show already-claimed on-chain rewards, but the live claim flow is not open there yet.':
    '이 화면은 선택한 wallet의 social airdrop 상태를 보여줍니다. 일반적인 transfer history가 아닙니다. 현재 live claim flow는 Telegram에서만 동작합니다. 앱이 wallet session을 시작하고 bot을 연 다음, 보상이 사용 가능한지, 대기열에 있는지, legacy claim으로 막혀 있는지, 이미 수령되었는지를 추적합니다.\n\nTelegram 카드는 세 가지 검사를 동시에 합칩니다. local wallet 상태, 현재 bot session 상태, 그리고 on-chain claim 상태입니다. 그래서 라벨이 available, verify now, session live, queued, received 사이를 오갈 수 있습니다.\n\n다른 social 카드는 지금은 rollout placeholder입니다. 이미 claimed된 on-chain 보상을 표시할 수는 있지만, live claim flow는 아직 열려 있지 않습니다.',
  'This screen reveals the signing key stored locally for this wallet. The key is never sent to 4TEEN servers during export.\n\nBefore the key is shown, the app requires passcode or biometrics. While it is visible, screenshots are blocked and the key hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with this private key can sign transactions from the wallet. Copy it only if you are storing it offline and securely.':
    '이 화면은 이 wallet을 위해 로컬에 저장된 signing key를 보여줍니다. Export 과정에서 이 key는 4TEEN 서버로 전송되지 않습니다.\n\nKey를 보여주기 전에 앱은 passcode 또는 생체인증을 요구합니다. Key가 보이는 동안에는 스크린샷이 차단되며, 1분이 지나거나 앱이 백그라운드로 가면 자동으로 숨겨집니다.\n\n이 private key를 가진 누구나 wallet에서 거래에 서명할 수 있습니다. 오프라인에서 안전하게 보관할 경우에만 복사하세요.',
  'This screen reveals the recovery phrase stored locally for this wallet. The phrase is never sent to 4TEEN servers during export.\n\nBefore the words are shown, the app requires passcode or biometrics. While the phrase is visible, screenshots are blocked and it hides automatically after one minute or when the app leaves the foreground.\n\nAnyone with these words can control the wallet. Copy them only if you are storing the phrase offline and securely.':
    '이 화면은 이 wallet을 위해 로컬에 저장된 recovery phrase를 보여줍니다. Export 과정에서 이 phrase는 4TEEN 서버로 전송되지 않습니다.\n\n단어를 보여주기 전에 앱은 passcode 또는 생체인증을 요구합니다. Phrase가 보이는 동안에는 스크린샷이 차단되며, 1분이 지나거나 앱이 백그라운드로 가면 자동으로 숨겨집니다.\n\n이 단어들을 가진 누구나 wallet을 제어할 수 있습니다. 오프라인에서 안전하게 보관할 경우에만 복사하세요.',
} as const;
