import type { SearchRouteEntry } from './search-types';

export const APP_SEARCH_ROUTES: SearchRouteEntry[] = [
  {
    id: 'route-create-import',
    route: '/ui-lab',
    title: 'Wallet Setup',
    subtitle: 'Create or import your first wallet',
    keywords: ['create wallet', 'import wallet', 'start', 'welcome', 'onboarding'],
    quickPageOrder: 1,
    quickPageVisibility: 'noWallets',
    quickPageIcon: 'addWallet',
  },
  {
    id: 'route-send',
    route: '/send',
    title: 'Send Crypto',
    subtitle: 'Transfer TRX or tokens',
    keywords: ['send', 'transfer', 'send crypto', 'send trx', 'send token'],
    quickPageOrder: 2,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'send',
  },
  {
    id: 'route-swap',
    route: '/swap',
    title: 'Token Swap',
    subtitle: 'Exchange assets inside wallet',
    keywords: ['swap', 'token swap', 'exchange', 'trade'],
    quickPageOrder: 3,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'swap',
  },
  {
    id: 'route-buy-4teen',
    route: '/buy-4teen',
    title: 'Buy 4TEEN',
    subtitle: 'Open the direct buy flow',
    keywords: ['buy 4teen', 'buy', 'purchase', 'direct buy'],
    quickPageOrder: 4,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'buy',
  },
  {
    id: 'route-unlock-timeline',
    route: '/unlock-timeline',
    title: 'Unlock Timeline',
    subtitle: 'View token unlock schedule',
    keywords: ['unlock', 'unlock timeline', 'vesting', 'locked tokens'],
    quickPageOrder: 5,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'unlock',
  },
  {
    id: 'route-liquidity-controller',
    route: '/liquidity-controller',
    title: 'Liquidity Control',
    subtitle: 'Open liquidity management tools',
    keywords: ['liquidity', 'liquidity control', 'liquidity controller', 'controller'],
    quickPageOrder: 6,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'liquidity',
  },
  {
    id: 'route-ambassador-program',
    route: '/ambassador-program',
    title: 'Ambassador Cabinet',
    subtitle: 'Open referral dashboard tools',
    keywords: ['ambassador', 'cabinet', 'ambassador cabinet', 'ambassador program', 'referral'],
    quickPageOrder: 7,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'ambassador',
  },
  {
    id: 'route-airdrop',
    route: '/airdrop',
    title: 'Airdrop Claim',
    subtitle: 'Open reward claim screen',
    keywords: ['airdrop', 'claim', 'reward', 'telegram airdrop'],
    quickPageOrder: 8,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'airdrop',
  },
  {
    id: 'route-select-wallet',
    route: '/select-wallet',
    title: 'Select Wallet',
    subtitle: 'Choose the active wallet',
    keywords: ['select wallet', 'choose wallet', 'active wallet'],
    quickPageOrder: 9,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-home',
    route: '/home',
    title: 'Open Home',
    subtitle: 'Go back to wallet home',
    keywords: ['home', 'main', 'wallet home'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-wallets',
    route: '/wallets',
    title: 'Open Wallets',
    subtitle: 'Manage, rename, remove, and open wallets',
    keywords: ['wallet', 'wallets', 'manage wallet', 'wallet management'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-address-book',
    route: '/address-book',
    title: 'Address Book',
    subtitle: 'View and manage saved contacts',
    keywords: ['contact', 'contacts', 'address book', 'addressbook'],
    quickPageIcon: 'send',
  },
  {
    id: 'route-manage-crypto',
    route: '/manage-crypto',
    title: 'Manage Crypto',
    subtitle: 'Toggle token visibility and manage assets',
    keywords: ['token', 'tokens', 'crypto', 'asset', 'assets', 'manage crypto'],
    quickPageIcon: 'swap',
  },
  {
    id: 'route-add-custom-token',
    route: '/add-custom-token',
    title: 'Add Token',
    subtitle: 'Add or enable a token by contract',
    keywords: ['custom token', 'add token', 'contract', 'token contract'],
    quickPageIcon: 'swap',
  },
  {
    id: 'route-settings',
    route: '/settings',
    title: 'App Settings',
    subtitle: 'Open app settings',
    keywords: ['setting', 'settings'],
    quickPageIcon: 'liquidity',
  },
  {
    id: 'route-about',
    route: '/about',
    title: 'About App',
    subtitle: 'Project and app information',
    keywords: ['about', 'about us', 'info'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-whitepaper',
    route: '/whitepaper',
    title: 'Whitepaper',
    subtitle: 'Read the whitepaper',
    keywords: ['whitepaper', 'paper', 'docs'],
    quickPageIcon: 'buy',
  },
  {
    id: 'route-terms',
    route: '/terms',
    title: 'Terms Page',
    subtitle: 'Read terms and conditions',
    keywords: ['terms', 'conditions', 'legal'],
    quickPageIcon: 'wallet',
  },
];
