import type { SearchRouteEntry } from './search-types';

export const APP_SEARCH_ROUTES: SearchRouteEntry[] = [
  {
    id: 'route-create-import',
    route: '/wallet-access',
    title: 'Wallet Setup',
    subtitle: 'Create or import your first wallet',
    keywords: ['create wallet', 'import wallet', 'start', 'welcome', 'onboarding'],
    aliases: ['new wallet', 'setup wallet', 'first wallet', 'create', 'import'],
    quickPageOrder: 1,
    quickPageVisibility: 'noWallets',
    quickPageIcon: 'addWallet',
  },
  {
    id: 'route-send',
    route: '/send',
    title: 'Send Crypto',
    subtitle: 'Choose token and recipient to transfer',
    keywords: ['send', 'transfer', 'send crypto', 'send trx', 'send token'],
    aliases: ['withdraw', 'payment', 'recipient', 'wallet send', 'send money'],
    quickPageOrder: 2,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'send',
  },
  {
    id: 'route-swap',
    route: '/swap',
    title: 'Token Swap',
    subtitle: 'Exchange assets inside wallet',
    keywords: ['swap', 'token swap', 'exchange', 'trade'],
    aliases: ['convert', 'change token', 'swap token', 'dex'],
    quickPageOrder: 3,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'swap',
  },
  {
    id: 'route-buy-4teen',
    route: '/buy-4teen',
    title: 'Buy 4TEEN',
    subtitle: 'Open the direct buy flow',
    keywords: ['buy 4teen', 'buy', 'purchase', 'direct buy'],
    aliases: ['purchase 4teen', 'buy token', 'buy coin'],
    quickPageOrder: 4,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'buy',
  },
  {
    id: 'route-earn',
    route: '/earn',
    title: 'Earn',
    subtitle: 'Open earning and rewards section',
    keywords: ['earn', 'rewards', 'yield', 'income', 'staking'],
    aliases: ['make money', 'earnings', 'profit', 'reward center'],
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'buy',
  },
  {
    id: 'route-unlock-timeline',
    route: '/unlock-timeline',
    title: 'Unlock Timeline',
    subtitle: 'View token unlock schedule',
    keywords: ['unlock', 'unlock timeline', 'vesting', 'locked tokens'],
    aliases: ['lock', 'unlocks', 'release schedule', 'vesting schedule'],
    quickPageOrder: 5,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'unlock',
  },
  {
    id: 'route-liquidity-controller',
    route: '/liquidity-controller',
    title: 'Liquidity Control',
    subtitle: 'Open liquidity management tools',
    keywords: ['liquidity', 'liquidity control', 'liquidity controller', 'controller'],
    aliases: ['lp', 'pool', 'liquidity manager', 'manage liquidity'],
    quickPageOrder: 6,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'liquidity',
  },
  {
    id: 'route-ambassador-program',
    route: '/ambassador-program',
    title: 'Ambassador Cabinet',
    subtitle: 'Open referral dashboard tools',
    keywords: ['ambassador', 'cabinet', 'ambassador cabinet', 'ambassador program', 'referral'],
    aliases: ['referrals', 'referral dashboard', 'affiliate', 'partners'],
    quickPageOrder: 7,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'ambassador',
  },
  {
    id: 'route-airdrop',
    route: '/airdrop',
    title: 'Airdrop Claim',
    subtitle: 'Open reward claim screen',
    keywords: ['airdrop', 'claim', 'reward', 'telegram airdrop'],
    aliases: ['claim reward', 'bonus', 'drop'],
    quickPageOrder: 8,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'airdrop',
  },
  {
    id: 'route-select-wallet',
    route: '/select-wallet',
    title: 'Select Wallet',
    subtitle: 'Choose the active wallet',
    keywords: ['select wallet', 'choose wallet', 'active wallet'],
    aliases: ['switch wallet', 'wallet picker', 'change wallet'],
    quickPageOrder: 9,
    quickPageVisibility: 'hasWallets',
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-home',
    route: '/wallet',
    title: 'Open Home',
    subtitle: 'Go back to wallet home',
    keywords: ['home', 'main', 'wallet home', 'wallet screen', 'portfolio'],
    aliases: ['dashboard', 'main screen', 'start screen', 'main wallet', 'wallet overview'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-wallets',
    route: '/wallet-manager',
    title: 'Open Wallets',
    subtitle: 'Manage, rename, remove, and open wallets',
    keywords: ['wallet', 'wallets', 'manage wallet', 'wallet management'],
    aliases: ['my wallets', 'wallet list', 'wallet manager'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-address-book',
    route: '/address-book',
    title: 'Address Book',
    subtitle: 'View and manage saved contacts',
    keywords: ['contact', 'contacts', 'address book', 'addressbook'],
    aliases: ['recipients', 'saved addresses', 'contact list'],
    quickPageIcon: 'send',
  },
  {
    id: 'route-scan',
    route: '/scan',
    title: 'Scan QR',
    subtitle: 'Scan wallet, address, or payment QR code',
    keywords: ['scan', 'scanner', 'qr', 'qr scan', 'camera'],
    aliases: ['scan qr', 'scan address', 'open camera', 'qr code'],
    quickPageIcon: 'send',
  },
  {
    id: 'route-browser',
    route: '/browser',
    title: 'DApp Browser',
    subtitle: 'Open websites and dapps inside wallet',
    keywords: ['browser', 'web', 'website', 'dapp', 'dapp browser', 'discover'],
    aliases: ['internet', 'site', 'open site', 'open dapp', 'webview', 'explore dapps'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-manage-crypto',
    route: '/manage-crypto',
    title: 'Manage Crypto',
    subtitle: 'Toggle token visibility and manage assets',
    keywords: ['token', 'tokens', 'crypto', 'asset', 'assets', 'manage crypto'],
    aliases: ['coin list', 'asset list', 'hidden tokens', 'visible tokens', 'manage tokens'],
    quickPageIcon: 'swap',
  },
  {
    id: 'route-add-custom-token',
    route: '/add-custom-token',
    title: 'Add Token',
    subtitle: 'Add or enable a token by contract',
    keywords: ['custom token', 'add token', 'contract', 'token contract'],
    aliases: ['import token', 'manual token', 'add asset', 'custom asset'],
    quickPageIcon: 'swap',
  },
  {
    id: 'route-settings',
    route: '/settings',
    title: 'App Settings',
    subtitle: 'Open app settings',
    keywords: ['setting', 'settings', 'app settings', 'preferences'],
    aliases: ['preferences', 'config', 'app config', 'options'],
    quickPageIcon: 'liquidity',
  },
  {
    id: 'route-appearance',
    route: '/appearance',
    title: 'Appearance',
    subtitle: 'Adjust visual preferences and interface look',
    keywords: ['appearance', 'theme', 'look', 'interface', 'display'],
    aliases: ['ui settings', 'design', 'style', 'visual settings'],
  },
  {
    id: 'route-language',
    route: '/language',
    title: 'Language',
    subtitle: 'Choose app language',
    keywords: ['language', 'locale', 'translation', 'app language'],
    aliases: ['change language', 'localization', 'idioma'],
  },
  {
    id: 'route-currency',
    route: '/currency',
    title: 'Currency',
    subtitle: 'Change fiat display currency',
    keywords: ['currency', 'fiat', 'usd', 'money format', 'display currency'],
    aliases: ['base currency', 'local currency', 'price currency'],
  },
  {
    id: 'route-auth-method',
    route: '/authentication-method',
    title: 'Authentication Method',
    subtitle: 'Manage passcode and biometric unlock settings',
    keywords: ['authentication', 'security', 'passcode', 'biometric', 'face id', 'fingerprint'],
    aliases: ['unlock settings', 'app lock', 'security settings', 'login method'],
  },
  {
    id: 'route-create-passcode',
    route: '/create-passcode',
    title: 'Create Passcode',
    subtitle: 'Set a new app passcode',
    keywords: ['create passcode', 'set passcode', 'new passcode', 'security code'],
    aliases: ['make passcode', 'create pin', 'set pin'],
  },
  {
    id: 'route-enable-biometrics',
    route: '/enable-biometrics',
    title: 'Enable Biometrics',
    subtitle: 'Turn on face unlock or fingerprint unlock',
    keywords: ['enable biometrics', 'biometrics', 'face unlock', 'fingerprint', 'face id'],
    aliases: ['turn on biometrics', 'enable fingerprint', 'enable face unlock'],
  },
  {
    id: 'route-unlock',
    route: '/unlock',
    title: 'Unlock App',
    subtitle: 'Open wallet with passcode or biometrics',
    keywords: ['unlock', 'unlock app', 'open wallet', 'login'],
    aliases: ['enter passcode', 'open app', 'sign in'],
  },
  {
    id: 'route-backup-private-key',
    route: '/backup-private-key',
    title: 'Export Private Key',
    subtitle: 'Reveal and export wallet private key',
    keywords: ['private key', 'export private key', 'export key', 'secret key'],
    aliases: ['show private key', 'wallet key', 'copy private key'],
  },
  {
    id: 'route-export-mnemonic',
    route: '/export-mnemonic',
    title: 'Export Seed Phrase',
    subtitle: 'Reveal and back up mnemonic phrase',
    keywords: ['seed phrase', 'mnemonic', 'recovery phrase', 'backup seed'],
    aliases: ['show seed', 'export seed', 'recovery words', '12 words', '24 words'],
  },
  {
    id: 'route-connections',
    route: '/connections',
    title: 'Connections',
    subtitle: 'Review connected apps and wallet access',
    keywords: ['connections', 'connected apps', 'sessions', 'linked apps', 'permissions'],
    aliases: ['walletconnect', 'connected dapps', 'authorized apps', 'app access'],
  },
  {
    id: 'route-multisig',
    route: '/multisig-transactions',
    title: 'Multisig Transactions',
    subtitle: 'Coming soon in the in-app browser flow',
    keywords: ['multisig', 'multi sig', 'multisignature', 'shared transaction'],
    aliases: ['co-sign', 'cosign', 'pending signatures', 'shared wallet tx'],
  },
  {
    id: 'route-create-wallet',
    route: '/create-wallet',
    title: 'Create Wallet',
    subtitle: 'Create a new signing wallet',
    keywords: ['create wallet', 'new wallet', 'generate wallet', 'create account'],
    aliases: ['make wallet', 'open new wallet', 'fresh wallet'],
  },
  {
    id: 'route-import-wallet',
    route: '/import-wallet',
    title: 'Import Wallet',
    subtitle: 'Choose a wallet import method',
    keywords: ['import wallet', 'restore wallet', 'recover wallet'],
    aliases: ['wallet import', 'restore access', 'recover account'],
  },
  {
    id: 'route-import-seed',
    route: '/import-seed',
    title: 'Import Seed Phrase',
    subtitle: 'Restore wallet from mnemonic phrase',
    keywords: ['import seed', 'seed phrase', 'mnemonic import', 'restore from phrase'],
    aliases: ['recover by seed', 'restore by words', 'import mnemonic'],
  },
  {
    id: 'route-import-private-key',
    route: '/import-private-key',
    title: 'Import Private Key',
    subtitle: 'Restore wallet from private key',
    keywords: ['import private key', 'private key', 'restore key'],
    aliases: ['recover by key', 'paste private key', 'wallet key import'],
  },
  {
    id: 'route-import-watch-only',
    route: '/import-watch-only',
    title: 'Import Watch-Only',
    subtitle: 'Add wallet address without signing access',
    keywords: ['watch only', 'watch-only', 'import address', 'read only wallet'],
    aliases: ['observe wallet', 'track wallet', 'address only wallet'],
  },
  {
    id: 'route-about',
    route: '/about',
    title: 'About App',
    subtitle: 'Project and app information',
    keywords: ['about', 'about us', 'info'],
    aliases: ['application info', 'project info'],
    quickPageIcon: 'wallet',
  },
  {
    id: 'route-whitepaper',
    route: '/whitepaper',
    title: 'Whitepaper',
    subtitle: 'Read the whitepaper',
    keywords: ['whitepaper', 'paper', 'docs'],
    aliases: ['documentation', 'project docs', 'token docs'],
    quickPageIcon: 'buy',
  },
  {
    id: 'route-terms',
    route: '/terms',
    title: 'Terms Page',
    subtitle: 'Read terms and conditions',
    keywords: ['terms', 'conditions', 'legal'],
    aliases: ['tos', 'legal page', 'rules'],
    quickPageIcon: 'wallet',
  },
];
