function optionalEnv(name, fallback = '') {
  const value = process.env[name];

  if (value === undefined || value === null) {
    return fallback;
  }

  const normalized = String(value).trim();
  return normalized === '' ? fallback : normalized;
}

function requiredEnv(name) {
  const value = optionalEnv(name, '');

  if (!value) {
    throw new Error(`Missing env: ${name}`);
  }

  return value;
}

function numberEnv(name, fallback) {
  const raw = optionalEnv(name, '');

  if (!raw) return fallback;

  const parsed = Number(raw);

  if (!Number.isFinite(parsed)) {
    throw new Error(`Invalid number env: ${name}`);
  }

  return parsed;
}

module.exports = {
  PORT: numberEnv('PORT', 3000),

  DATABASE_URL: optionalEnv('DATABASE_URL', ''),
  LEGACY_TELEGRAM_BOT_DATABASE_URL: optionalEnv('LEGACY_TELEGRAM_BOT_DATABASE_URL', ''),
  TELEGRAM_LEGACY_HASH_SALT: optionalEnv('TELEGRAM_LEGACY_HASH_SALT', ''),
  TELEGRAM_BOT_TOKEN: optionalEnv('TELEGRAM_BOT_TOKEN', ''),
  TELEGRAM_BOT_USERNAME: optionalEnv('TELEGRAM_BOT_USERNAME', ''),
  TELEGRAM_WEBHOOK_SECRET: optionalEnv('TELEGRAM_WEBHOOK_SECRET', ''),
  TELEGRAM_WEBHOOK_BASE_URL: optionalEnv('TELEGRAM_WEBHOOK_BASE_URL', ''),
  TELEGRAM_GROUP_ID: optionalEnv('TELEGRAM_GROUP_ID', '-1003375405784'),
  TELEGRAM_CHANNEL_ID: optionalEnv('TELEGRAM_CHANNEL_ID', '-1003233193685'),
  TELEGRAM_GROUP_URL: optionalEnv('TELEGRAM_GROUP_URL', 'https://t.me/+wsIZ1b1LtPExNjMx'),
  TELEGRAM_CHANNEL_URL: optionalEnv('TELEGRAM_CHANNEL_URL', 'https://t.me/fourteentoken'),
  TRON_FULL_HOST: optionalEnv('TRON_FULL_HOST', 'https://api.trongrid.io'),
  TRON_PRIVATE_KEY: optionalEnv('TRON_PRIVATE_KEY', ''),
  OPERATOR_WALLET_PRIVATE_KEY: optionalEnv('OPERATOR_WALLET_PRIVATE_KEY', ''),
  MANAGER_WALLET_PRIVATE_KEY: optionalEnv('MANAGER_WALLET_PRIVATE_KEY', ''),
  TRONGRID_API_KEY: optionalEnv('TRONGRID_API_KEY', ''),
  TRONGRID_API_KEY_1: optionalEnv('TRONGRID_API_KEY_1', ''),
  TRONGRID_API_KEY_2: optionalEnv('TRONGRID_API_KEY_2', ''),
  TRONGRID_API_KEY_3: optionalEnv('TRONGRID_API_KEY_3', ''),
  TRONSCAN_API_KEY: optionalEnv('TRONSCAN_API_KEY', ''),
  TRONSCAN_API_KEY_1: optionalEnv('TRONSCAN_API_KEY_1', ''),
  TRONSCAN_API_KEY_2: optionalEnv('TRONSCAN_API_KEY_2', ''),
  TRONSCAN_API_KEY_3: optionalEnv('TRONSCAN_API_KEY_3', ''),
  CMC_API_KEY: optionalEnv('CMC_API_KEY', ''),
  CMC_API_KEY_1: optionalEnv('CMC_API_KEY_1', ''),
  CMC_API_KEY_2: optionalEnv('CMC_API_KEY_2', ''),
  CMC_API_KEY_3: optionalEnv('CMC_API_KEY_3', ''),

  FOURTEEN_TOKEN_CONTRACT: optionalEnv('FOURTEEN_TOKEN_CONTRACT', 'TMLXiCW2ZAkvjmn79ZXa4vdHX5BE3n9x4A'),
  FOURTEEN_CONTROLLER_CONTRACT: optionalEnv('FOURTEEN_CONTROLLER_CONTRACT', 'TF8yhohRfMxsdVRr7fFrYLh5fxK8sAFkeZ'),
  AMBASSADOR_PENDING_QUEUE_LIMIT: numberEnv('AMBASSADOR_PENDING_QUEUE_LIMIT', 25),
  AMBASSADOR_ALLOCATION_REQUIRED_ENERGY: numberEnv('AMBASSADOR_ALLOCATION_REQUIRED_ENERGY', 120000),
  AMBASSADOR_ALLOCATION_REQUIRED_BANDWIDTH: numberEnv('AMBASSADOR_ALLOCATION_REQUIRED_BANDWIDTH', 500),
  AMBASSADOR_ALLOCATION_MIN_ENERGY_FLOOR: numberEnv('AMBASSADOR_ALLOCATION_MIN_ENERGY_FLOOR', 100),
  AMBASSADOR_ALLOCATION_MIN_BANDWIDTH_FLOOR: numberEnv('AMBASSADOR_ALLOCATION_MIN_BANDWIDTH_FLOOR', 10),
  AMBASSADOR_ALLOCATION_FEE_LIMIT_SUN: numberEnv('AMBASSADOR_ALLOCATION_FEE_LIMIT_SUN', 180_000_000),

  ADMIN_SYNC_TOKEN: optionalEnv('ADMIN_SYNC_TOKEN', ''),
  ALLOWED_ORIGINS: optionalEnv(
    'ALLOWED_ORIGINS',
    'https://4teen.me,https://www.4teen.me,http://localhost:3000,http://127.0.0.1:3000'
  ),

  GASSTATION_ENABLED: optionalEnv('GASSTATION_ENABLED', 'false'),
  GASSTATION_API_BASE_URL: optionalEnv('GASSTATION_API_BASE_URL', 'https://openapi.gasstation.ai'),
  GASSTATION_API_KEY: optionalEnv('GASSTATION_API_KEY', ''),
  GASSTATION_API_SECRET: optionalEnv('GASSTATION_API_SECRET', ''),
  GASSTATION_API_KEY_1: optionalEnv('GASSTATION_API_KEY_1', ''),
  GASSTATION_API_SECRET_1: optionalEnv('GASSTATION_API_SECRET_1', ''),
  GASSTATION_API_KEY_2: optionalEnv('GASSTATION_API_KEY_2', ''),
  GASSTATION_API_SECRET_2: optionalEnv('GASSTATION_API_SECRET_2', ''),
  GASSTATION_API_KEY_3: optionalEnv('GASSTATION_API_KEY_3', ''),
  GASSTATION_API_SECRET_3: optionalEnv('GASSTATION_API_SECRET_3', ''),
  GASSTATION_CREDENTIALS_JSON: optionalEnv('GASSTATION_CREDENTIALS_JSON', ''),
  GASSTATION_SERVICE_CHARGE_TYPE: optionalEnv('GASSTATION_SERVICE_CHARGE_TYPE', '10010'),
  GASSTATION_ENERGY_RENTAL_MODE: optionalEnv('GASSTATION_ENERGY_RENTAL_MODE', ''),
  GASSTATION_RENTAL_MARKUP_BPS: numberEnv('GASSTATION_RENTAL_MARKUP_BPS', 3000),
  GASSTATION_RENTAL_MIN_MARKUP_SUN: numberEnv('GASSTATION_RENTAL_MIN_MARKUP_SUN', 1_000_000),
  GASSTATION_MIN_BANDWIDTH: numberEnv('GASSTATION_MIN_BANDWIDTH', 5000),
  GASSTATION_MIN_ENERGY: numberEnv('GASSTATION_MIN_ENERGY', 64400),
  GASSTATION_REGISTRATION_ENERGY: numberEnv('GASSTATION_REGISTRATION_ENERGY', 100000),
  GASSTATION_REGISTRATION_ENERGY_MODE: optionalEnv('GASSTATION_REGISTRATION_ENERGY_MODE', 'api'),
  GASSTATION_RESALE_REGISTRATION_PAYMENT_ADDRESS: optionalEnv('GASSTATION_RESALE_REGISTRATION_PAYMENT_ADDRESS', ''),
  GASSTATION_RESALE_REGISTRATION_AMOUNT_SUN: optionalEnv('GASSTATION_RESALE_REGISTRATION_AMOUNT_SUN', ''),
  GASSTATION_RESALE_REGISTRATION_AMOUNT_TRX: optionalEnv('GASSTATION_RESALE_REGISTRATION_AMOUNT_TRX', ''),
  GASSTATION_RESALE_REGISTRATION_READY_ENERGY: numberEnv('GASSTATION_RESALE_REGISTRATION_READY_ENERGY', 90000),
  GASSTATION_RESALE_PACKAGES_JSON: optionalEnv('GASSTATION_RESALE_PACKAGES_JSON', ''),
  GASSTATION_DEPOSIT_ADDRESS: optionalEnv('GASSTATION_DEPOSIT_ADDRESS', ''),
  GASSTATION_BACKGROUND_REPLENISH_RESERVE_SUN: numberEnv(
    'GASSTATION_BACKGROUND_REPLENISH_RESERVE_SUN',
    1_000_000
  ),
  QUOTAGUARDSTATIC_URL: optionalEnv('QUOTAGUARDSTATIC_URL', ''),
  OPERATOR_WALLET: optionalEnv('OPERATOR_WALLET', 'TN95o1fsA7mNwJGYGedvf3y7DJZKLH6TCT'),
  AIRDROP_CONTROL_WALLET: optionalEnv('AIRDROP_CONTROL_WALLET', 'TQt7e4cbCU7cTVAvhNC6Na5T55BYAk5fUy'),
  AIRDROP_CONTROL_WALLET_PRIVATE_KEY: optionalEnv('AIRDROP_CONTROL_WALLET_PRIVATE_KEY', ''),
  AIRDROP_VAULT_CONTRACT: optionalEnv('AIRDROP_VAULT_CONTRACT', 'TV6eXKWCsZ15c3Svz39mRQWtBsqvNNBwpQ'),
  SITE_PUBLIC_AMBASSADOR_TTL_SECONDS: numberEnv('SITE_PUBLIC_AMBASSADOR_TTL_SECONDS', 120),
  SITE_PUBLIC_AIRDROP_TTL_SECONDS: numberEnv('SITE_PUBLIC_AIRDROP_TTL_SECONDS', 120),
  SITE_PUBLIC_BUY_TTL_SECONDS: numberEnv('SITE_PUBLIC_BUY_TTL_SECONDS', 120),
  SITE_PUBLIC_LIQUIDITY_TTL_SECONDS: numberEnv('SITE_PUBLIC_LIQUIDITY_TTL_SECONDS', 120),
  SITE_PUBLIC_MARKET_TTL_SECONDS: numberEnv('SITE_PUBLIC_MARKET_TTL_SECONDS', 120),
  SITE_PUBLIC_MIN_REFRESH_INTERVAL_SECONDS: numberEnv('SITE_PUBLIC_MIN_REFRESH_INTERVAL_SECONDS', 45),
  SITE_PUBLIC_SUMMARY_TTL_SECONDS: numberEnv('SITE_PUBLIC_SUMMARY_TTL_SECONDS', 120),
  SITE_PUBLIC_SWAP_TTL_SECONDS: numberEnv('SITE_PUBLIC_SWAP_TTL_SECONDS', 120),
  SITE_PUBLIC_UNLOCK_TTL_SECONDS: numberEnv('SITE_PUBLIC_UNLOCK_TTL_SECONDS', 120),
  SITE_PUBLIC_VERIFICATION_TTL_SECONDS: numberEnv('SITE_PUBLIC_VERIFICATION_TTL_SECONDS', 120),
  TELEGRAM_AIRDROP_MIN_REWARD: numberEnv('TELEGRAM_AIRDROP_MIN_REWARD', 1.000001),
  TELEGRAM_AIRDROP_MAX_REWARD: numberEnv('TELEGRAM_AIRDROP_MAX_REWARD', 4.999999),
  TELEGRAM_AIRDROP_REQUIRED_ENERGY: numberEnv('TELEGRAM_AIRDROP_REQUIRED_ENERGY', 60302),
  TELEGRAM_AIRDROP_REQUIRED_BANDWIDTH: numberEnv('TELEGRAM_AIRDROP_REQUIRED_BANDWIDTH', 378),
  TELEGRAM_AIRDROP_MIN_ENERGY_FLOOR: numberEnv('TELEGRAM_AIRDROP_MIN_ENERGY_FLOOR', 100),
  TELEGRAM_AIRDROP_MIN_BANDWIDTH_FLOOR: numberEnv('TELEGRAM_AIRDROP_MIN_BANDWIDTH_FLOOR', 10)
};
