export const APP_HEADER_HEIGHT = 52;
export const APP_HEADER_TOP_PADDING = 10;
export const APP_HEADER_DROP_OFFSET = 2;
export const APP_HEADER_TOTAL_HEIGHT = APP_HEADER_TOP_PADDING + APP_HEADER_DROP_OFFSET + APP_HEADER_HEIGHT;
export const APP_HEADER_SIDE_PADDING = 20;
export const APP_MENU_TOP_GAP = 10;
